require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/EmptyMethod:
  EnforcedStyle: expanded
